"""Dash app styles."""

from src.dash_app.styles.tab_styles import (
    TAB_BUTTON_BASE_STYLE,
    TAB_BUTTON_SELECTED_STYLE,
    TAB_BUTTON_UNSELECTED_STYLE,
    TAB_CONTENT_VISIBLE_STYLE,
    TAB_CONTENT_HIDDEN_STYLE,
)

__all__ = [
    "TAB_BUTTON_BASE_STYLE",
    "TAB_BUTTON_SELECTED_STYLE",
    "TAB_BUTTON_UNSELECTED_STYLE",
    "TAB_CONTENT_VISIBLE_STYLE",
    "TAB_CONTENT_HIDDEN_STYLE",
]
